### PR TITLE
 remove direct references to variable SLIPSTREAM_REPORT_DIR

### PR DESCRIPTION
**Pull request by loomis**
Update physical connector for removal of SLIPSTREAM_REPORT_DIR java variable.

Connected to slipstream/SlipStreamClient#106.

### CODE REVIEW

**Comment by loomis** [comment]
I've merged this PR to get the Jenkins builds to pass.  Please verify that the changes are correct or if they're not, please revert this and then do the proper correction.

**Comment by konstan** [comment]
@loomis Just FYI. Updated with 1d205bcf10ecd47db16e8223d43d9e2a24f27e6f

**Comment by schaubl** [comment]
Sorry, I merged the one in the server and I didn't saw this one.

**Comment by schaubl** [comment]
In fact I just realized that this PR wasn't existent when I merged the other one.

**Comment by konstan** [comment]
Yes, this was discovered by @loomis later in the evening after you merged the other one that removed the field from the base class.  The build of Physical connector in jenkins started failing.
However, I initially thought that Physical connector was temporarily disabled for build as well. 
@loomis Are we still building/shipping it?

**Comment by loomis** [comment]
The code is still in the repository, so yes it is built and packaged.  Removing the connector and the code is OK for me.

**Pull request merged**
