### PR TITLE
allow dict or object for _vm_get_ip/id

### PR DESCRIPTION
**Pull request by konstan**
Connected to #173

### CODE REVIEW

**Comment by schaubl** [comment]
This is not the right way to fix it.

The issue is not in the CloudStack connector but in the SlipStreamClient (`CloudWrapper._get_failed_instances_on_iaas()`)

The method `_start_image()` of a connector has to return an object representing the started VM.
The type of this object is the responsibility of the connector but it has to provide some methods that can extract some specific informations from this object (eg: `_vm_get_id()`, `_vm_get_ip()`, ...). In the documentation of these methods, it's explicitly written that they take as input a value returned by `_start_image()`.

Other methods are made to work on elements of the list returned by the `list_instances()` method (eg: `_vm_get_state()`, `_vm_get_ip_from_list_instances()`, `_vm_get_cpu()`, ...).

As you can see there are two methods to retrieve the IP. One for the object returned by `_start_image()` (`_vm_get_ip()`) and one for the element in the list returned by `list_instances()` (`_vm_get_ip_from_list_instances()`)

The issue there is that the method `_get_failed_instances_on_iaas()` calls the `list_instances()` method of the connector and then try to get the VM ID by calling `_vm_get_id()` which is not made for that. 
Instead `_get_failed_instances_on_iaas()` should call `_vm_get_id_from_list_instances()` but unfortunately this method doesn't exist.
So the correct fix is to implement this method and use it inside of the method `_get_failed_instances_on_iaas()`.

Some pointers:
- [Method `_get_failed_instances_on_iaas()`](https://github.com/slipstream/SlipStreamClient/blob/fad206ce7652d896c3d0a870b5872881b939756b/client/src/main/python/slipstream/wrappers/CloudWrapper.py#L265-L281)
- [Connector interface](https://github.com/slipstream/SlipStreamClient/blob/30387150e42ab9e21ea31d2ebf3523c9f0a98f73/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L47-L151)

**Comment by konstan** [comment]
The idea was to make _vm_get_id/ip polymorphic allowing to accept input of different types - dict (the default) and an object on which `id` field is defined.  The latter applies to the Node object of libcloud.  This removes the need for overriding those methods in the child classes of CloudConnectorBase.

**Comment by konstan** [comment]
I agreed, that for IP this might be trickier.  
But at the same time, for that specific case with CloudStack and failing to extract cloud ID this PR IMHO fixes this call
https://github.com/slipstream/SlipStreamClient/blob/fad206ce7652d896c3d0a870b5872881b939756b/client/src/main/python/slipstream/wrappers/CloudWrapper.py#L277

**Comment by konstan** [comment]
> This removes the need for overriding those methods in the child classes of CloudConnectorBase.
Ignore this wrong statement in https://github.com/slipstream/SlipStreamConnectors/pull/174#issuecomment-336382627.

**Comment by schaubl** [comment]
This PR fix only the issue with CloudStack based Clouds.
The same kind of fix should also be done in all others connectors

**Comment by konstan** [comment]
Yes, sure.  And that is why it's connected to #173, which is for cloudstack only.  Although the implementation of `_vm_get_id` will work with any libcloud based one.  With multiple inheritance in python we can have new LibcloudBased class that would implement the overloaded getters and then `class CloudStackClientCloud(LibcloudBased, BaseCloudConnector)` (and similarly for others).
Let me know how do see us proceeding with this PR: 1. leave the fix as it is or 2. generalise to libcloud based connectors.  Thanks.

**Comment by konstan** [comment]
Closing this PR.  A fix was provided in https://github.com/slipstream/SlipStreamClient/pull/361.  A followup issue proposing a more generic solution is here https://github.com/slipstream/SlipStreamClient/issues/362

**Pull request closed without merging**
